include:
  - board: nice_nano_v2
    shield: pig_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: pig_right nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: settings_reset