include:
  - board: nice_nano_v2
    shield: pig_left nice_view_adapter nice-shield-p
  - board: nice_nano_v2
    shield: pig_right nice_view_adapter nice-shield-p
    cmake-args:
      - DCONFIG_ZMK_KEYBOARD_NAME=\"pig!\"
  - board: nice_nano_v2
    shield: settings_reset