file_format: "1"
id: pig
name: pig!
type: shield
url: https://github.com/chase-hunter/pig
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - pig_left
  - pig_right